# coding: utf -8
# PROG1 - UFCG
# ALUNO: EMANUEL VINICIUS | DATA: 16/12/2021  
# MATRICULA: 120210785
# EXERCICIO: PROGRAMA QUE TRANSFORMA GRAUS EM RADIANOS

import math

#|ENTRADAS| EM FLOATS - REPRESENTANDO O VALOR EM GRAUS
graus = float(input())

#|FÓRMULAS E CALCULOS| EQUAÇÃO PARA TRANSFORMAR GRAUS -> RADIANOS
rad = (math.pi/180) * graus

#|SAIDA| SEM PROMPTS
print(f"{rad:.3f}")
